### ISSUE TITLE
Cannot convert value of type 'Dictionary<String, [String]>' to expected argument type 'OrderedDictionary<String, [String?]>'

### ISSUE THREAD

**Issue by saroar** [pointfreeco/vapor-routing#19]
<img width="933" alt="Screenshot 2022-11-08 at 12 29 51" src="https://user-images.githubusercontent.com/8770772/200527936-073faf91-ae7a-45c0-8233-494496a82345.png">
dont know why its error cant build project now :(

**Comment by stephencelis** [comment]
@saroar Sorry about that! Looks like an update from URL Routing 0.4.0 got in the way. We'll merge #20 to fix and cut a new release soon.

**Comment by stephencelis** [comment]
Fixed in 0.1.2. Please upgrade your package!
